### ISSUE TITLE
Enabler: stage-to-lower create test sites

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgdp-management-tools#53]
# Create test sites for QA automation testing.

When staging to a lower tier environment, create sites from a configured list.

> **ESTIMATE** TBD

### Prerequisites
- #51

**Comment by bryanpizzillo** [comment]
@blairlearn Some more definition around this item...
* There are 2 automation sites for testing. One to ensure `blt drupal:update` works and one for new installs.
   * `www-XXX-acsf/automation-installed` is for testing new installs.
      * The site name in ACSF should be `automation0installed`
   * `www-XXX-acsf/automation-refreshed` is for testing updates.
      * The site name in ACSF should be `automation0refreshed`
* Immediately after staging an environment the `www-XXX-acsf/automation-refreshed` site should be created.
   * @kate-mashkina will need to weight in if ODE content is created at this point or AFTER the code deployment. This is because YAML content is in the code. 
      * Issues installing content before Code: 
         * If the new code contains new YAML or changes to the YAML regression tests will fail. 
      * Issues installing content after Code:
         * If the upgrade modifies content then installing if after the code update will not flag those issues.
* Only after deploying code should the `www-XXX-acsf/automation-installed` be created.
